### ISSUE TITLE
Product Detail API

### ISSUE THREAD

**Issue by yothinix** [yothinix/assignment-java-boot-camp#2]
## API Spec
https://github.com/yothinix/assignment-java-boot-camp/blob/main/documents/apis/product-detail.md

## Todo
- [x] Product Image Repository
- [x] Product Variant Repository
- [x] Product Review Repository
- [x] Get Product by id in service
- [x] Product Detail controller
